"use client"

import { CategoryType, CategoryWithIcon } from "@/types/types"
import { BookA, BotIcon, FileType, FolderOpen, Globe, GraduationCap, HeartIcon, History, Library, NotebookPenIcon, PenTool, ReceiptText, Rss, Trash2 } from "lucide-react"


export const defaultCategories: CategoryWithIcon[] = [
  {
    id: "library",
    name: "我的文库",
    type: CategoryType.Papers,
    favorited: false,
    archived: false,
    parentId: "text",
    icon: Library,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  // {
  //   id: "webs",
  //   name: "学术网站",
  //   type: CategoryType.Others,
  //   favorited: false,
  //   archived: false,
  //   parentId: "text",
  //   icon: Globe,
  //   createdAt: new Date(Date.now()),
  //   updatedAt: new Date(Date.now()),
  // },
  {
    id: "notes",
    name: "我的笔记",
    type: CategoryType.Markdowns,
    favorited: false,
    archived: false,
    parentId: "",
    icon: NotebookPenIcon,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: "favorites",
    name: "收藏夹",
    type: CategoryType.Others,
    favorited: false,
    archived: false,
    parentId: "text",
    icon: HeartIcon,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: "trash",
    name: "回收站",
    type: CategoryType.Others,
    favorited: false,
    archived: false,
    parentId: "text",
    icon: Trash2,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: "ai",
    name: "AI助手",
    type: CategoryType.Others,
    favorited: false,
    archived: false,
    parentId: "tool",
    icon: BotIcon,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: "recents",
    name: "最近阅读",
    type: CategoryType.Papers,
    favorited: false,
    archived: false,
    parentId: "library",
    icon: History,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },

  {
    id: "whiteboards",
    name: "白板",
    type: CategoryType.Whiteboards,
    favorited: false,
    archived: false,
    parentId: "notes",
    icon: PenTool,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: "vocabularies",
    name: "单词本",
    type: CategoryType.Others,
    favorited: false,
    archived: false,
    parentId: "notes",
    icon: BookA,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: "terms",
    name: "专业术语",
    type: CategoryType.Others,
    favorited: false,
    archived: false,
    parentId: "notes",
    icon: FileType,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    id: "sentences",
    name: "精彩句式",
    type: CategoryType.Others,
    favorited: false,
    archived: false,
    parentId: "notes",
    icon: ReceiptText,
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  // {
  //   id: "googlescholar",
  //   name: "谷歌学术",
  //   type: CategoryType.Others,
  //   favorited: false,
  //   archived: false,
  //   parentId: "webs",
  //   icon: GraduationCap,
  //   createdAt: new Date(Date.now()),
  //   updatedAt: new Date(Date.now()),
  // },
  // {
  //   id: "semanticscholar",
  //   name: "SemanticScholar",
  //   type: CategoryType.Others,
  //   favorited: false,
  //   archived: false,
  //   parentId: "webs",
  //   icon: FolderOpen,
  //   createdAt: new Date(Date.now()),
  //   updatedAt: new Date(Date.now()),
  // },
  // {
  //   id: "arxiv",
  //   name: "Arxiv",
  //   type: CategoryType.Others,
  //   favorited: false,
  //   archived: false,
  //   parentId: "webs",
  //   icon: ReceiptText,
  //   createdAt: new Date(Date.now()),
  //   updatedAt: new Date(Date.now()),
  // },
]